version: '3.3'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - ALLOWED_HOSTS=127.0.0.1,localhost,ec2-18-130-120-248.eu-west-2.compute.amazonaws.com,18.130.120.248
      - DB_HOST=db
      - DB_NAME=user_db
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - DB_HOST=db
      - DB_NAME=user_db
      - DB_USER=postgres
      - DB_PASS=supersecretpassword


  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data:
  postgres_data: