# Generated by Django 3.1.5 on 2021-02-09 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('SALARY', 'SALARY'), ('FREELANCE', 'FREELANCE'), ('RENTAL', 'RENTAL'), ('BUSINESS', 'BUSINESS'), ('OTHERS', 'OTHERS')], max_length=255),
        ),
    ]
